### ISSUE TITLE
Template-Feld klein machen

### ISSUE THREAD

**Issue by sheepyhollow** [Larsg7/pdfcreator_frontend#15]
Das Template-Bedienfeld mit Ändern, Hochladen, Runterladen, Löschen nimmt relativ viel Platz auf der Oberfläche ein und wird bei der Arbeit mit den Daten nicht mehr gebraucht. Könnte man das in ein eigenes Fenster packen und nur einen "Editieren"-Button in der Template-Zeile belassen?

**Comment by sheepyhollow** [comment]
Ich bin darüberhinaus auch nicht sicher, ob der "neue Template"-Button rechts unten so sinnvoll ist (von dem MD-Empfehlungen abgesehen), denn wenn ich eine Template offen habe und mit dieser arbeite, interessieren mich vor allem die Daten und die Felder. In diesem Arbeitsschritt will ich eigentlich gar keine neue Template anlegen. 
Könnte man da nicht "neue Template anlegen" auch in das Template-Auswahlmenü als Menüpunkt einbauen? Aber mit den UX-Guidelines von MD will ich mich nun auch nicht anlegen :)

**Comment by larsgroeber** [comment]
Der Plus Button bleibt wo er ist! ;)
Aber die Bearbeiten Buttons verschwinden jetzt in einem Expansion Panel, wenn das Template ein Dokument hat.
