### ISSUE TITLE
Bug: globale Felder

### ISSUE THREAD

**Issue by sheepyhollow** [Larsg7/pdfcreator_frontend#16]
Wenn man im Serien-Modus globale Felder einführt, werden diese - offenbar - als neue Felder angefügt. Man erkennt dies nach "generieren" in der Feldliste; dort werden die globalen Felder nicht ersetzt, sondern stehen als weitere Felder weiter unten.

In der Vorschau bzw. Dokument werden die neuen globalen Daten nicht ersetzt, dort stehen nur die Feldnamen, da nur die ersten (leeren) Felder kompiliert werden.

**Comment by larsgroeber** [comment]
Fixed in #17
