### ISSUE TITLE
Serie bearbeiten

### ISSUE THREAD

**Issue by sheepyhollow** [Larsg7/pdfcreator_frontend#7]
Wenn ich eine Serie generiert habe - wie kann ich die Felder bearbeiten?
Ich sollte diese noch editieren können, so dass ich wieder die Tabelle sehen und einzelne Werte ändern kann.

**Comment by larsgroeber** [comment]
Ich kann die letzten Werte speichern, so dass man die Serie direkt wieder sieht. 
Wie würdest du es handhaben, wenn sich das Template ändert? Das einfachste wäre natürlich, die Serie dann zu löschen, man könnte sich aber auch einen (vmtl relativ komplizierten) Algorithmus überlegen, der überprüft, ob noch Werte verwendbar sind.

**Comment by larsgroeber** [comment]
Added in #13
