### ISSUE TITLE
Zeichensatz-Fehler in CSV

### ISSUE THREAD

**Issue by sheepyhollow** [Larsg7/pdfcreator_frontend#8]
Ist es möglich, Zeichensatzfehler vorher abzufangen und nicht erst beim Generieren der Serie?

Kann man den Zeichensatz eigentlich auslesen und automatisch konvertieren bzw. nach UTF-8 casten?

**Comment by larsgroeber** [comment]
Was für eine Art von Zeichensatzfehler meinst du? Funktioniert das Generieren der Serie nicht oder gibt es einen Fehler im generierten PDF?

**Comment by sheepyhollow** [comment]
Siehe Problem von heute (27.02.). Das Generieren schlägt fehl, wenn falsch codierte Zeichen (Umlaute etc.) enthalten sind.

**Comment by sheepyhollow** [comment]
![image](https://user-images.githubusercontent.com/13869236/44329993-2fc72580-a466-11e8-897b-b8846be9e35f.png)

Das passiert, wenn das File ISO-8859-2 oder ANSI codiert ist. Mit UTF-8 werden die Umlaute korrekt ausgelesen.

Am schönsten wäre es, wenn die Tabelle beim Einlesen automatisch konvertiert wird. Gibt es da keinen klassischen Weg?

**Comment by larsgroeber** [comment]
Befürchte, da gibt es keinen Weg, das automatisch zu machen. Hatte ein bisschen was ausprobiert, aber ohne Erfolg...

**Comment by sheepyhollow** [comment]
Wäre es wenigstens möglich, die Codierung automatisch zu erkennen und eine Meldung zu schmeißen?
Oder in das Upload-Fenster den Hinweis schreiben, dass man UTF-8 nehmen soll?
Ich hatte sowas hier gesehen aber nicht die Codebasis dazu gefunden: https://www.browserling.com/tools/utf8-encode
