### ISSUE TITLE
.CSV-Endung erlauben

### ISSUE THREAD

**Issue by sheepyhollow** [Larsg7/pdfcreator_frontend#9]
Wenn das File .csv heißt kommt ein Filetype not allowed-Fehler. Warum?
Mit .txt funktioniert es.

**Comment by larsgroeber** [comment]
Das scheint ein Problem auf Windows zu sein, auf Linux funktioniert eine .csv Datei...
Ich schaue es mir an.

**Comment by larsgroeber** [comment]
Auf Windows ist der Typ einer .csv Datei `application/vnd.ms_excel`...
Ich habe den Check auf den Typ entfernt.
